name: Pipeline CI/CD

on:
  push:
    branches: 
      - main 

permissions: 
  id-token: write
  contents: read

jobs: 
  job1:
    name: build_ecr
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::255982107351:role/GithubActionsRepoApp
          aws-region: us-east-2

      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build Image, Tag and Push para Amazon ECR
        run: |
          VERSION=1.0.${{ github.run_number }}

          IMAGE_URI=255982107351.dkr.ecr.us-east-2.amazonaws.com/site_hmg_toledo

          docker build -t $IMAGE_URI:$VERSION .
          docker push $IMAGE_URI:$VERSION

  job2:
    name: deploy_ec2
    needs: job1
    env: 
      INSTANCE_KEY: ${{secrets.INSTANCE_KEY}}
      PUBLIC_IP: ${{secrets.PUBLIC_IP}}
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy EC2 SSH
        run: |
          echo "$iNSTANCE_KEY" > chave-site.pem
          chmod 400 chave-site.pem
          ssh -i chave-site.pem -o StrictHostKeyChecking=no ec2-user@$PUBLIC_IP << EOF
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 255982107351.dkr.ecr.us-east-2.amazonaws.com
              docker pull \$IMAGE_URI:\$VERSION
              docker stop site || true
              docker rm site || true
              docker run -d -p 80:80 --name site \$IMAGE_URI:\$VERSION
          EOF
          rm chave-site.pem 
